{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "634f15c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing sheet: Routers\n",
      "Processing sheet: IP Camera \n",
      "Processing sheet: Power Supplies\n",
      "Processing sheet: Audio Equipment\n",
      "Processing sheet: Memory and Flash\n",
      "Processing sheet: Network Video Recorders\n",
      "Processing sheet: Data Tape\n",
      "Processing sheet: Software License\n",
      "Processing sheet: Network Security\n",
      "Processing sheet: Security Cameras\n",
      "Processing sheet: Video Conferencing\n",
      "Processing sheet: Business Application\n",
      "Processing sheet: Adapter\n",
      "Processing sheet: Converter\n",
      "Processing sheet: POE Injector\n",
      "Processing sheet: UC Solutions\n",
      "Processing sheet: Ip Phones\n",
      "Processing sheet: SSD \n",
      "Processing sheet: Cables\n",
      "Processing sheet: Storage System\n",
      "Processing sheet: Workstations\n",
      "Processing sheet: Motherboards\n",
      "Processing sheet: Desktop Computers\n",
      "Processing sheet: Expansion Card\n",
      "Processing sheet: Servers\n",
      "Processing sheet: Hard drives\n",
      "Processing sheet: Laptop\n",
      "Processing sheet: Cooling Solutions\n",
      "Processing sheet: Server Rack\n",
      "Processing sheet: Processors\n",
      "Processing sheet: Memory\n",
      "Data saved to final_product_data12.json\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import json\n",
    "import os\n",
    "\n",
    "# Function to process and clean up product data from a sheet\n",
    "def process_product_data_from_sheet(df):\n",
    "    # Remove leading/trailing spaces in column names\n",
    "    df.columns = df.columns.str.strip()\n",
    "\n",
    "    # Drop rows with any null values\n",
    "    df = df.dropna()\n",
    "\n",
    "    # Drop duplicate rows across all columns\n",
    "    df = df.drop_duplicates()\n",
    "\n",
    "    # Return cleaned DataFrame\n",
    "    return df\n",
    "\n",
    "# Function to combine data from all product sheets in the Excel file\n",
    "def combine_product_data_from_sheets(file_path):\n",
    "    combined_data = pd.DataFrame()\n",
    "\n",
    "    # Read the Excel file\n",
    "    excel_file = pd.ExcelFile(file_path)\n",
    "\n",
    "    # Loop through all sheets in the Excel file\n",
    "    for sheet_name in excel_file.sheet_names:\n",
    "        print(f\"Processing sheet: {sheet_name}\")\n",
    "        \n",
    "        # Read the sheet into a DataFrame\n",
    "        df = pd.read_excel(excel_file, sheet_name=sheet_name)\n",
    "\n",
    "        # Process and clean the data from the sheet\n",
    "        sheet_data = process_product_data_from_sheet(df)\n",
    "        \n",
    "        # Combine this sheet's cleaned data with the combined_data DataFrame\n",
    "        combined_data = pd.concat([combined_data, sheet_data], ignore_index=True)\n",
    "    \n",
    "    # Remove duplicates across the combined data from all sheets\n",
    "    combined_data = combined_data.drop_duplicates()\n",
    "\n",
    "    return combined_data\n",
    "\n",
    "# Function to convert the DataFrame into the required JSON format\n",
    "def convert_to_json_format(df):\n",
    "    # Create a dictionary to hold the final JSON structure\n",
    "    filter_dict = {}\n",
    "\n",
    "    # Group by 'WebAttribute filter name' and collect unique 'Filter Value' for each\n",
    "    for _, row in df.iterrows():\n",
    "        filter_name = row['WebAttribute filter name']\n",
    "        filter_value = row['Filter Value']\n",
    "\n",
    "        if filter_name not in filter_dict:\n",
    "            filter_dict[filter_name] = []\n",
    "\n",
    "        # Add filter value to the list, if it's not already present\n",
    "        if filter_value not in filter_dict[filter_name]:\n",
    "            filter_dict[filter_name].append(filter_value)\n",
    "\n",
    "    # Prepare the JSON structure\n",
    "    final_json = [{\"Filter Name\": key, \"Filter Values\": values} for key, values in filter_dict.items()]\n",
    "    \n",
    "    return final_json\n",
    "\n",
    "# Function to save the final JSON data to a file\n",
    "def save_to_json(data, output_file):\n",
    "    with open(output_file, 'w') as json_file:\n",
    "        json.dump(data, json_file, indent=4)\n",
    "    print(f\"Data saved to {output_file}\")\n",
    "\n",
    "# File path for your Excel file with multiple sheets\n",
    "input_file = 'Router Attribute (2) (1).xlsx'  # Update this to your actual file path\n",
    "\n",
    "# Combine product data from all sheets in the Excel file\n",
    "combined_data = combine_product_data_from_sheets(input_file)\n",
    "\n",
    "# Convert the data into the required JSON format\n",
    "final_json = convert_to_json_format(combined_data)\n",
    "\n",
    "# Save the final JSON data to a file\n",
    "output_file = 'final_product_data1.json'\n",
    "save_to_json(final_json, output_file)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2789e97b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
